//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public string Weather1 { get; set; }
        public int IdState { get; set; }
    
        public virtual State State { get; set; }
    }
}
